language: java
script: cd CommunityJavaServerREST && mvn install

#language: android
#jdk: oraclejdk8
#android:
#  components:
#    - platform-tools
#    - tools
#    - build-tools-29.0.2
#    - android-29

#script: cd CommunityAndroidClient && ./gradlew build
